package:
  name: mirax_profileinfo_extractor
  version: "0.2.2"

source:
  path: ../  # This assumes the Conda recipe directory is adjacent to your source code


build:
  number: 0
  script:
    - gcc lib/profileinfo_extractor.c -shared -fPIC -o libprofileinfo_extractor.so -O3
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - configparser
    - {{ compiler('c') }}
  run:
    - python

about:
  home: https://github.com/pathologywatch/mirax_profileinfo_extractor
  license: MIT
  license_file: LICENSE
  summary: 'This simple lib helps extract extra information from Mirax files that are not provided by other open source libraries like Openslide.'

extra:
  recipe-maintainers:
    - ekami
